include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'


# LLVM with assertions

asserts:1.3:
  extends:
    - .julia:source
    - .test
  variables:
    CI_CLONE_ARGS: '-b v1.3.1'
    CI_BUILD_ARGS: 'BINARYBUILDER_LLVM_ASSERTS=1 LLVM_BB_URL_BASE=https://github.com/staticfloat/LLVMBuilder/releases/download/v6.0.1-7+nowasm/'
    CI_ASSERTS: 'true'

# TODO: upgrade to 1.4.1 once it has LLVM+asserts artifacts
asserts:1.4:
  extends:
    - .julia:source
    - .test
  variables:
    CI_CLONE_ARGS: '-b v1.4.0'
    CI_BUILD_ARGS: 'BINARYBUILDER_LLVM_ASSERTS=1'
    CI_ASSERTS: 'true'

# TODO: add 1.5.0 once it has LLVM+asserts artifacts


# CUDA.jl

.test_cuda:
  extends: .test
  variables:
    JULIA_NUM_THREADS: '2'
    JULIA_CUDA_USE_BINARYBUILDER: 'false' # reduce CI network traffic
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="CUDA", rev="master"));
                Pkg.test("CUDA");'

cuda:1.4:
  extends:
    - .julia:1.4
    - .test_cuda
  tags:
    - nvidia
  allow_failure: true


# AMDGPUnative.jl

.test_amdgpunative:
  extends: .test
  image: rocm/dev-ubuntu-18.04
  script:
    - julia -e 'using Pkg;
                Pkg.develop(PackageSpec(path=pwd()));
                Pkg.build();'
    - julia -e 'using Pkg;
                Pkg.add(PackageSpec(name="AMDGPUnative", rev="jps/gpucompiler"));
                Pkg.test("AMDGPUnative");'

amdgpunative:1.4:
  extends:
    - .julia:1.4
    - .test_amdgpunative
  tags:
    - rocm
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.4
    - .coverage
